config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"


  resources :sessions
  delete '/logout' => 'sessions#destroy'

  resources :users

  resources :posts do
    resources :comments
  end

  resources :cities

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :posts
  has_many :users, through: :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_length_of :title, :minimum => 1, :maximum => 200
  validates_length_of :content, :allow_blank => false
  
  post = Post.new
  post.valid?
  post.errors[:title]
  post.errors.full_messages

  belongs_to :user
  belongs_to :city

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :email, uniqueness: true
  validates_length_of :first_name, :allow_blank => false
  validates_length_of :last_name, :allow_blank => false
  validates_length_of :location, :allow_blank => false

  has_many :posts
  has_many :cities, through: :posts

  user = User.new
  user.valid? 
  user.errors[:email]
  user.errors.full_messages

  user.errors.clear
  user.errors.empty? 
  # def a_method_used_for_validation_purposes
  # 	errors.add(:email, "Email is already taken!")
  # end

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   def current_user
      @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
    end 
  include SessionsHelper
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all.order(:name)
    render :index
  end

  def show
    @city = City.find(params[:id])
    @cities = City.all
    @posts = Post.where(city_id: @city).order(created_at: :DESC)
    # @user = User.find(current_user)
    @current_user= current_user
    @post = Post.new
    render :show
  end

  def new
    @city = City.new
    render :new
  end

  def create
    city_params = params.require(:city).permit(:name, :image)
    @city = City.create(city_params)
    redirect_to @city # <-- go to city
  end

  def edit
    @city = City.find(params[:id])
    render :edit
  end

  def update          
    @city = City.find(params[:id])
    updated_attributes = params.require(:city).permit(:name, :image)
    @city.update_attributes(updated_attributes)
    redirect_to @city 
  end

  def destroy
    @user = User.find(current_user)
    City.destroy(params[:id])
    redirect_to @user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    comment_params = params.require(:comment).permit(:content, :post_id)
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comment = Comment.find_by_id(params[@post.comment_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    @cities = City.all
    @user = User.find(current_user)

    render :new
  end

  def create
    post_params = params.require(:post).permit(:title, :content, :user_id, :city_id)
    @post = Post.create(post_params)
    @current_user= current_user
    @cities = City.all
    @post.user_id = @current_user.id
    if @post.save
      redirect_to @post # <-- go to post
    else 
      render :new
    end
   

  end

  def show
    @post = Post.find_by_id(params[:id])
    @user = User.find_by_id(@post.user_id)
    @city = City.find_by_id(@post.city_id)
    @cities = City.all
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    @user = User.find(current_user)
    @cities = City.all
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    post_params = params.require(:post).permit(:title, :content)
    @post.update_attributes(post_params)
    @cities = City.all
    redirect_to @post
  end

  def destroy
    @user = User.find(current_user)
    Post.destroy(params[:id])
    @cities = City.all
    redirect_to @user
  end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
		render :new
	end

	 def create

    user_params = params.require(:user).permit(:email, :password)
    # byebug
    @user = User.confirm(user_params)
    if @user
      login(@user)
      redirect_to @user
    else
      redirect_to new_session_path
    end
  end



  def destroy
      logout
    redirect_to root_path 
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
		render :new
	end 

	def show
		@user = User.find(params[:id])
		render :show
	end

	def create
  	user_params = params.require(:user).permit(:first_name, :last_name, :location, :email, :password)
  	@user = User.new(user_params)
    if @user.save
  	 login(@user) # <-- login the user
  	 redirect_to user_path(@user) # <-- go to show
    else
      render :new
    end
  end

	def edit
    @user = User.find(params[:id])
    render :edit
	end

	def update 	   	    
    @user = User.find(params[:id])
    updated_attributes = params.require(:user).permit(:first_name, :last_name, :location, :image_url)
    @user.update_attributes(updated_attributes)
    redirect_to @user 
	end

    # def index
    #   @user = User.new
    #   render :new
    # end

    private
      def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@user = User.new
		@cities = City.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def _error_messages_for(user=nil)
		render(partial: 'layouts/error_messages', user: user) unless user.blank?
	end
	
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	 def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user 
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      # redirect_to new_session_path
    else
      true
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cities/edit.html.erb
<%= form_for @city do |f| %>

  <%= f.text_field  :name, class:"form-control", placeholder: "City Name" %> 
  <%= f.text_field :image, class:"form-control", placeholder: "Image URL" %>
  <%= f.submit "Update Post", class:"btn btn-primary btn-lg pull-right" %>

<% end %>

app/views/cities/index.html.erb
<h1>All the Cities that have been visited:</h1>

<!-- Create a new city -->
<h2>Have you been somewhere new?</h2>
<button>Add a city!</button>



<div class="container">
  <div class="row city_display">  
    <% @cities.each do |city| %>
      <div class="col-sm-3">
        <div class="thumbnail">
            <div class="caption">
            <%= link_to city_path(city) do %>
              <img src="<%=city.image%>" >
            <%end%>
            <h3><%=city.name%></h3>
            <p><%= link_to "View City", city_path(city) %> </p>
            <!-- TODO: add how many posts there are per city -->
            </div>
        </div>
      </div>
    <% end %>
  </div> 
</div>

app/views/cities/new.html.erb
<section class='intro'>
<div class="col-sm-10 col col-sm-offset-1 well clearfix">
<%= form_for @city do |f| %>
  
  <div>
    <h3>Add a new City:</h3>
    <%= f.text_field :name, class:"form-control", placeholder: "City Name" %>
  </div>
  
  <div>
    <h3>Image of City:</h3>
    <%= f.text_field :image, class:"form-control", placeholder: "Image URL - Find a picture you like on the web, right click and hit copy image url" %>
    <%=f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <%= f.submit "Submit", class:"btn btn-primary btn-lg pull-right" %>

<% end %>
</div>
  
</section>

app/views/cities/show.html.erb
<div class="jumbotron">
    <iframe id="kitty" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCYDJAwjEnJEDEHD0q7zobrgd7XhkR871o
    &q=<%=@city.name%>"></iframe>
</div>
<div class="container">
<!-- City picture and add post form-->
  <div class="row">
    <div class="col-sm-5 city_image"> 
    <h1 class="cityName"><%=@city.name%></h1>
    <!-- city image -->
    <img src="<%= @city.image %>">
    </div>
<% if current_user %>
    <div class="col-sm-7">
      <div class="well city_post_form clearfix">
      <h2>Create a new Post for <%=@city.name %></h2>
        <%= form_for @post do |f|  %>
          <div>
            <%= f.text_field :title, class:"form-control", placeholder: "Title" %> </br>
            <%= f.text_area :content, class:"form-control", placeholder: "Content" %>
            <!-- grab the id of the city through current page -->
            <%=f.hidden_field :city_id, :value => @city.id %>

            <!-- grab user id by session  -->
            <%=f.hidden_field :user_id, :value => current_user.id %>
          </div>
          <%= f.submit "Submit", class:"btn btn-primary btn-lg pull-right" %>
        <% end %>
        
      </div>
    </div>
    <% end %>
  </div>
</div>
    <div class="container">
      <div class="row city_posts">
        <h2>What do other have to say about this city</h2>
        <% @posts.each do |post| %>
          <div class='col-sm-2'>
          <img class='postpic' src='<%= User.find(post.user_id).image_url %>'>
          </div>
          <div class='col-sm-10 well'>
            <h3><%= link_to "#{post.title}", post_path(post) %></h3>
            <p><%=post.content%></p>
          </div>
        <% end %>
    </div>
    </li>
  </ul>
</div>

app/views/comments/new.html.erb
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_error_messages.html.erb
<% content_for :_error_messages do %>
  

  <ul>
    <% if @user.errors.any? %> 
        <p>
          <%= pluralize(@user.errors.count, "error") %> prevented the form from being saved:
        </p>
      <% @user.errors.full_messages.each do |message| %> 
        <li><%= message %></li>
        
      <% end %> 
    <% end %> 
  </ul>
<% end %> 

app/views/layouts/_nav.html.erb
<nav id='nav' class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="logo navbar-brand" href="/">Travel Chatter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %> 
        <% @user = current_user %> 
        <li><a href="/users/<%=@user.id%>"><%= "Welcome #{@user.first_name}" %></a></li>
        <li><a href="/posts/new">Create New Post</a></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
      <% else %> 
        <li><%= link_to "Log in", new_session_path, method: :get %></li>
      <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vagabond</title>


 <!-- Fonts -->
  
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

 <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller], 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

</head>
<body>
<%=render partial: "layouts/nav"%>
<%= yield %>
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

    markers = handler.addMarkers([
      {
        "lat": 37.774929,
        "lng": -122.419416,
        "picture": {
          "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
          "width":  36,
          "height": 36
        },
        "infowindow": "hello!"
      },
      {
        "lat": 32.715738,
        "lng": -117.161084,
        "picture": {
          "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
          "width":  36,
          "height": 36
        },
        "infowindow": "hello!"
      },
      {
        "lat": 32.715738,
        "lng": -117.161084,
        "picture": {
          "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
          "width":  36,
          "height": 36
        },
        "infowindow": "hello!"
      },
      {
        "lat": 32.715738,
        "lng": -117.161084,
        "picture": {
          "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
          "width":  36,
          "height": 36
        },
        "infowindow": "hello!"
      }
    ]);
  	 
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

//   var cities = new Array(
//         'Dorćol, Belgrade, Serbia',
//         'Dorćol, Belgrade, Serbia',
//         'Dorćol, Belgrade, Serbia',
//         'Rome, Italy',
//         'Rome, Italy');

// var gmarkers = [];
// mc = new MarkerClusterer(map, [], mcOptions);

// for (i=0; i<cities.length; i++) {
//    var ptStr = cities[i];
//    var newAddress;

//     //Key Part Here!!! These should be cached somewhere rather than querying every page refresh like here though.
//     geocoder.geocode( { 'address': cities[i] }, function(results, status) {
//     if (status == google.maps.GeocoderStatus.OK) {
//         newAddress = results[0].geometry.location;
//         var latlng = new google.maps.LatLng(parseFloat(newAddress.lat()),parseFloat(newAddress.lng()));
//         gmarkers.push(createMarker(latlng,content[i]));
//     }
// 	}
// } }
</script>
</body>
<footer>
  Made by Team Awesome
</footer>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>

  <%= f.text_field  :title, class:"form-control", placeholder:"Title" %> 
  <%= f.text_area :content, class:"form-control", placeholder:"Content" %>
  <%= f.submit "Update Post", class:"btn btn-primary btn-lg pull-right" %>

<% end %>

app/views/posts/new.html.erb
<div class="container">
  <div id='newPostForm' class="col-md-12">
    <h1>Post to one of our cities below<br> <small>or create a new city <%= link_to "here", new_city_path %> :</small></h1>
    <div class="well clearfix">
     
      <%= form_for @post do |f| %>

      <ul>
        <% if @post.errors.any? %> 
        <p>
          <%= pluralize(@post.errors.count, "error") %> prevented the form from being saved:
        </p>
        <% @post.errors.full_messages.each do |message| %> 
        <li><%= message %></li>

        <% end %> 
        <% end %> 
      </ul>
      
        <div>
          <h3>Create a title for your post:</h3>
          <p>This should help other users have a good idea about what your post topic is about.</p>
          <%= f.text_field :title, class:"form-control", placeholder: "Title" %>
        </div>
        <div>
          <h3>Information to share:</h3>
          <p>The information below should give insight to other users interested in a specific city.  This can include resturant reviews, places to visit, tours to go on or just a general overview.</p>
          <%= f.text_area :content, class:"form-control", placeholder: "Content" %>
          <%=f.hidden_field :user_id, :value => current_user.id %>
        </div>
        <div id="cityDropDown">
          <h3>Pick a city below</h3>
          <%= fields_for (@cities) do |c| %>
            <div class= 'field'>
              <%= c.label "All Cities" %> </br>
              <%= f.collection_select :city_id, @cities, :id, :name, include_blank: true %>
            </div>
          <% end %>
        </div>

        <%= f.submit "Submit", class:"btn btn-primary btn-lg pull-right" %>
      <% end %>
      
    </div>
  </div>
  
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm-4 postImg">
      <%= link_to city_path(@city) do %>
        <img src="<%=@city.image%>" >
      <%end%>
      
      <div>
        <%= link_to "View City", city_path(@city) %> 
      </div>
      
      <div>
        <!-- TODO: should display the author of post -->
        <p>Author: <%= User.find(@post.user_id).first_name %> <%= User.find(@post.user_id).last_name %></p>
      </div>


    </div>

    <div class="col-sm-8">
      <h1><%= @post.title %></h1>
      <p><%= @post.content %></p>
      <!-- TODO customization:  when this is the current users post display editing buttons -->
      <% if session[:user_id] == @user.id %>
        <div class="row">
          <%= button_to "Edit Post", edit_post_path, class:"pairBtn btn btn-default raised", method: :get %> 
          <%= button_to "Delete Post", post_path, class:"pairBtn btn btn-default", method: :delete %>
        </div>
      <% end %>

      <!-- Show Comments -->
       <div class="row">
       <h2> Comments: </h2>
        <ul>
          <% @post.comments.each do |c| %>
          <li> <%= c.content %> </li>
          <% end %>
        </ul>
      </div>
      <!-- Add Comment Form -->
      <div class="row">
        <h2>Add a comment:</h2>
        <%= form_for([@post, @post.comments.build]) do |f| %>
          <div class="field">
            <%= f.text_area :content %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
      <!--  -->

    </div>


    <!-- TODO customization:  when this is not the current users post display add comment forms -->


  </div>
</div>

app/views/users/edit.html.erb
<section class='intro'>
  <div class="col-sm-8 col-sm-offset-2 well">
  <h2>Edit your profile below:</h2>
    <%= form_for @user do |f| %>

        <%= f.text_field  :first_name, class:"form-control", placeholder:"First name" %> 
        </br>
        <%= f.text_area :last_name, class:"form-control", placeholder:"Last name" %>
        </br>
        <%= f.text_field :location, class:"form-control", placeholder:"Home city"%>
        </br>
        <%= f.text_field :image_url, class:"form-control", placeholder:"Find a picture you like, right click and hit copy image url"%>
        <%= f.submit "Update Profile", class:"btn close pull-right" %>

    <% end %>
  </div>
</section>

app/views/users/new.html.erb
<section class='intro'>
  <div class="col-sm-8 col-sm-offset-2 well">
  <h1>Sign up for Travel Chatter</h1>
  	<%= form_for @user do |f| %>
    	<ul>
    		<% if @user.errors.any? %> 
      		<p>
      			<%= pluralize(@user.errors.count, "error") %> prevented the form from being saved:
      		</p>
      		<% @user.errors.full_messages.each do |message| %> 
      		<li><%= message %></li>
      		<% end %> 
    		<% end %> 
    	</ul>
  	<%= f.label :first_name %> 
  	<%= f.text_field :first_name, placeholder: "First Name", class:'form-control', autofocus: true %> 
  	<br>
  	<%= f.label :last_name %> 
  	<%= f.text_field :last_name, placeholder: "Last Name", class:'form-control' %> 
  	<br> 
  	<%= f.label :location %>
  	<%= f.text_field :location, placeholder: "location", class:'form-control'%> 
  	<br> 
    <%= f.label :image_url %>
    <%= f.text_field :image_url, placeholder: "Find a picture you like, right click and hit copy image url", class:'form-control'%> 
    <br> 
  	<%= f.label :email %> 
  	<%= f.text_field :email, class:'form-control' %>
  	<br>
  	<%= f.label :password %> 
  	<%= f.password_field :password, class:'form-control' %>
  	<br>
  	<div class="text-right">
  		<%= f.submit "Sign Up", class: 'btn btn-primary' %> 
  	</div>
  	<% end %> 
  </div>
</section>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 profile_pic">
      <img src="<%= @user.image_url %>">
      <br> 
      <h4><%= "#{@user.first_name} #{@user.last_name}"  %> </h4>
      <br>
      <p><%= "Joined on #{@user.created_at.to_date.to_formatted_s(:long_ordinal)}" %></p>
      <br>
      <p><%= "Home City: #{@user.location}" %></p>
      <!-- TODO change to link to specific user -->
      <%=link_to "Edit profile", edit_user_path, class:"btn btn-primary" %>
    </div>
    <div class="col-sm-8">
      <!-- TODO run loop for all posts here -->
      <ul>
        <% @user.posts.each do |p| %> 
        <li>
          <div class="well clearfix">
            <h3><%= link_to "#{p.title}", post_path(p) %></h3>
            <br>
            <p><%= p.content %> </p>
            <br>
            <%= button_to "Edit Post", edit_post_path(p), class:"pairBtn btn close", method: :get %>
            <%= button_to "Delete Post", post_path(p), class:"pairBtn btn close", method: :delete %>
          </div>
        </li>
        <% end %> 
      </ul>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<section id='splash'class='intro'>
  <div id='welcome' class="container content">
    <div class="row">
      
      <div class="col-sm-6">
        <%= image_tag ('splash.gif'), class: "img-responsive"%>
      </div>

      <div id='splash_content' class="col-sm-6">
        <h1>Travel Chatter</h1>
        <h3>A place for people to leave posts about places they have been, things they have seen or things they have done around the world.</h3>
        <!-- TODO change to link to sign up page -->
        <%= button_to "Sign Up", new_user_path, class:"btn btn-default", method: :get %>
        <p class="btn">Join the chatter and make an account</p>
      </div>
    </div>
  </div> 
</section> 

<section>
  <div class="container">
  <h2>Cities people are talking about:</h2>
    <div class="row ">  
      <% @cities.each do |city| %>
        <div class="col-sm-3 city_display">
          <div class="thumbnail img-responsive">
          <%= link_to city_path(city) do %>
            <img src="<%=city.image%>" >
          <%end%>
               <center><h3><%=city.name%></h3></center>
              <div  class="caption">
                <p align="right"><%= link_to "View City", city_path(city) %> </p>
              </div>
          </div>
        </div>
      <% end %>
    </div> 
  </div> 
</section>  


<section>
    <div id="splash_map" class="row">

      <div class="col-sm-8">
        <div id="map"> 
        </div>
      </div>

      <div class="col-sm-4">
        <div class="well">
        <h5>looking for a specific city?</h5>

          <!-- TODO: add google Querry form -->
        </div>
      </div>
    
    </div>
</section>


    

    